"""create client preferences table

Revision ID: 40d806d150e6
Revises: f2429e51d0ae
Create Date: 2026-08-23 12:11:39.819449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d806d150e6'
down_revision: Union[str, Sequence[str], None] = 'f2429e51d0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('listing_type', sa.String(length=20), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_bedrooms', sa.Integer(), nullable=True),
    sa.Column('min_bathrooms', sa.Integer(), nullable=True),
    sa.Column('min_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_preferences')
    # ### end Alembic commands ###
