"""add is_active to clients

Revision ID: ef11a4f4bd3c
Revises: d4326681bb5d
Create Date: 2026-08-22 11:49:27.206662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef11a4f4bd3c'
down_revision: Union[str, Sequence[str], None] = 'd4326681bb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
